name: WakaTime Coding Statistics

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  update-Readme:
    name: Automatically update my README  
    runs-on: ubuntu-latest
    steps:
      - uses: taller-programacion/C@v1.0.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_MONTHLY: true
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_ACTION: ${{ github.action }}
